name: Update Calendar for Today

on:
  push:
    branches:
      - release
  schedule:
    # Run every day 05:00 UTC+9
    - cron: "0 20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_calendar:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release
      - name: Install dependencies
        run: |
          pip3 install --upgrade argparse oauth2client google-api-python-client
      - name: Call google calendar API and save result
        run: |
          python3 bin/call-google-calendar-api.py \
            --key ${{ secrets.GOOGLE_CALENDAR_API_KEY }} \
            --output assets/json/calendar.json \
            --calendars \
              iu1iul1u3n8ic3s78f4df15u4o@group.calendar.google.com \
              c_kmvgs6pqta7man27ikg08ffrhc@group.calendar.google.com
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update calendar for today
          branch: gh-pages
          file_pattern: assets/json/calendar.json
          create_branch: true
